### ISSUE TITLE
RF footprint needs to be improved

### ISSUE THREAD

**Issue by JaredWatson** [waterloo-rocketry/canhw#22]
Currently the RF footprint used on the GPS board and the Live Telemetry board had extremely small pads that make soldering it a pain in the butt. In the future the amount of soldering space should probably be expanded (but not enough to shrink the space of the RF trace, it's already smaller than 120 mils and we don't want to lose that sweet sweet RF integrity).

**Comment by QuantumManiac** [comment]
I did a bit of testing, and it seems like it's pretty simple to have different sized pads on different layers.

In the _Pad Properties_ window, there's a Copper setting which allows you to change the layers that the copper and other layers are on for the pad:
![image](https://user-images.githubusercontent.com/8643561/81575435-07d3d000-9375-11ea-86b3-967c392c2a10.png)

My solution is to overlap two pads at each through-hole, with one pad having F.Cu and F.Mask and the other B.Cu and B.Mask 

Here's a view of a modified SMA connector in the footprint editor modified using the above method:
![image](https://user-images.githubusercontent.com/8643561/81575647-423d6d00-9375-11ea-88d5-d5957f690a35.png)
Notice that while the front pads are 2.2 mm, the back ones are much larger, at 3 mm 

3D Views - front and back comparison:
![image](https://user-images.githubusercontent.com/8643561/81576405-37370c80-9376-11ea-96d1-b686675f7087.png)

If I got some measurements for what the pads should be on each side, I would be happy to modify the footprint.

**Comment by JaredWatson** [comment]
Looks good, I'll leave a more formal review on the actual PR. This is definitely the footprint people should be using for SMA stuff in the future.
