### ISSUE TITLE
Mini sensor issues

### ISSUE THREAD

**Issue by zx100x100** [waterloo-rocketry/canhw#30]
1. The PTC fuse values should be labelled

2. this board could really do with some SMD test points.

**Comment by zx100x100** [comment]
MCLR silkscreen does not indicate MCLR voltage

**Comment by rdakhil** [comment]
some ground test points would be nice to have in the next respin

also standoffs are there in the CAD but they are very thin. the plating should be changed to be about as thick as the mounting holes

**Comment by JasonBrave** [comment]
Clock source(oscillator) is not isolated, result interference from CAN, cause PIC think external oscillator failure.

**Comment by BluCodeGH** [comment]
Recent comments are not addressed.

**Comment by Joe-Joe-Joe-Joe** [comment]
Has this board not been respun since this issue was raised?
